/**
 * Payroll Snapshot - Single Source of Truth
 *
 * Generated once during Payroll Processing
 * Immutable after creation
 * Shared across HR, Super Admin, and Accounts
 *
 * @component
 */

import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "../ui/card";
import { Badge } from "../ui/badge";
import { Button } from "../ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "../ui/table";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "../ui/dialog";
import {
  Database,
  Eye,
  Send,
  CheckCircle,
  XCircle,
  Lock,
  AlertCircle,
  Calendar,
  Users,
  DollarSign,
} from "lucide-react";
import { toast } from "sonner";
import { useRole } from "../../contexts/RoleContext";
import { formatCurrency } from "../../lib/formatters";

// Snapshot status workflow
export type SnapshotStatus =
  | "draft"           // Generated by Payroll Processing
  | "pending_hr"      // Ready for HR review
  | "pending_admin"   // Sent to Super Admin
  | "approved"        // Approved by Super Admin
  | "rejected"        // Rejected by Super Admin
  | "paid";           // Processed by Accounts

// Employee payroll snapshot (immutable)
export interface EmployeePayrollSnapshot {
  snapshotId: string;
  employeeId: string;
  employeeName: string;
  role: string;
  bankName?: string;
  accountNumber?: string;
  ifscCode?: string;
  units: number;
  validUnits: number;
  complianceScore: number;
  basePay: number;
  incentive: number;
  complianceAdjustment: number;
  deductions: number;
  totalPay: number;
  generatedAt: string;
  generatedBy: string;
}

// Payroll snapshot (batch of employees)
export interface PayrollSnapshot {
  id: string;
  month: string;
  year: string;
  city?: string;
  cluster?: string;
  status: SnapshotStatus;
  employees: EmployeePayrollSnapshot[];
  totalEmployees: number;
  totalPayout: number;
  generatedAt: string;
  generatedBy: string;
  sentToAdminAt?: string;
  sentToAdminBy?: string;
  approvedAt?: string;
  approvedBy?: string;
  rejectedAt?: string;
  rejectedBy?: string;
  rejectionReason?: string;
}

interface PayrollSnapshotViewProps {
  snapshot: PayrollSnapshot;
  onSendToAdmin?: () => void;
  onApprove?: () => void;
  onReject?: (reason: string) => void;
  viewMode: "hr" | "admin" | "accounts";
}

export function PayrollSnapshotView({
  snapshot,
  onSendToAdmin,
  onApprove,
  onReject,
  viewMode,
}: PayrollSnapshotViewProps) {
  const { currentRole } = useRole();
  const [selectedEmployee, setSelectedEmployee] = useState<EmployeePayrollSnapshot | null>(null);
  const [showDetailDialog, setShowDetailDialog] = useState(false);
  const [showRejectDialog, setShowRejectDialog] = useState(false);
  const [rejectionReason, setRejectionReason] = useState("");


  const getStatusBadge = (status: SnapshotStatus) => {
    const styles = {
      draft: "bg-gray-100 text-gray-700",
      pending_hr: "bg-blue-100 text-blue-700",
      pending_admin: "bg-purple-100 text-purple-700",
      approved: "bg-green-100 text-green-700",
      rejected: "bg-red-100 text-red-700",
      paid: "bg-teal-100 text-teal-700",
    };

    const labels = {
      draft: "Draft",
      pending_hr: "Pending HR Review",
      pending_admin: "Pending Admin Approval",
      approved: "Approved",
      rejected: "Rejected",
      paid: "Paid",
    };

    return <Badge className={styles[status]}>{labels[status]}</Badge>;
  };

  const handleViewDetails = (employee: EmployeePayrollSnapshot) => {
    setSelectedEmployee(employee);
    setShowDetailDialog(true);
  };

  const handleSendToAdmin = () => {
    if (onSendToAdmin) {
      onSendToAdmin();
      toast.success("Payroll snapshot sent to Super Admin for approval");
    }
  };

  const handleApprove = () => {
    if (onApprove) {
      onApprove();
      toast.success("Payroll snapshot approved");
    }
  };

  const handleReject = () => {
    if (!rejectionReason.trim()) {
      toast.error("Please provide a rejection reason");
      return;
    }
    if (onReject) {
      onReject(rejectionReason);
      setShowRejectDialog(false);
      setRejectionReason("");
      toast.success("Payroll snapshot rejected");
    }
  };

  return (
    <div className="space-y-6">
      {/* Snapshot Header */}
      <Card>
        <CardContent className="p-3 sm:p-6">
          <div className="flex items-start justify-between">
            <div>
              <h3 className="text-lg font-bold text-gray-900 mb-2">
                Payroll Snapshot #{snapshot.id}
              </h3>
              <div className="flex items-center gap-4 text-sm text-gray-600">
                <div className="flex items-center gap-2">
                  <Calendar className="w-4 h-4" />
                  {snapshot.month} {snapshot.year}
                </div>
                <div className="flex items-center gap-2">
                  <Users className="w-4 h-4" />
                  {snapshot.totalEmployees} Employees
                </div>
                <div className="flex items-center gap-2">
                  <DollarSign className="w-4 h-4" />
                  Total: {formatCurrency(snapshot.totalPayout)}
                </div>
              </div>
            </div>
            <div className="flex flex-col items-end gap-2">
              {getStatusBadge(snapshot.status)}
              <Badge variant="outline" className="flex items-center gap-1">
                <Lock className="w-3 h-3" />
                Read-Only Snapshot
              </Badge>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Immutable Notice */}
      <div className="flex items-center gap-3 p-3 bg-orange-50 border border-orange-200 rounded-lg">
        <Lock className="w-5 h-5 text-orange-600" />
        <div className="flex-1">
          <p className="text-sm font-medium text-orange-900">Snapshot Data (Immutable)</p>
          <p className="text-xs text-orange-700">
            This snapshot was generated on {snapshot.generatedAt} by {snapshot.generatedBy}.
            Values cannot be modified after generation.
          </p>
        </div>
      </div>

      {/* HR View: Full Details */}
      {viewMode === "hr" && (
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle className="text-base">Employee Payroll Details</CardTitle>
              {snapshot.status === "pending_hr" && onSendToAdmin && (
                <Button onClick={handleSendToAdmin}>
                  <Send className="w-4 h-4 mr-2" />
                  Send to Super Admin
                </Button>
              )}
            </div>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Employee</TableHead>
                  <TableHead>Role</TableHead>
                  <TableHead className="text-right">Units</TableHead>
                  <TableHead className="text-center">Compliance</TableHead>
                  <TableHead className="text-right">Base Pay</TableHead>
                  <TableHead className="text-right">Incentive</TableHead>
                  <TableHead className="text-right">Total Pay</TableHead>
                  <TableHead className="text-center">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {snapshot.employees.map((employee) => (
                  <TableRow key={employee.snapshotId}>
                    <TableCell>
                      <div className="font-medium">{employee.employeeName}</div>
                      <div className="text-xs text-gray-500">{employee.employeeId}</div>
                    </TableCell>
                    <TableCell className="text-sm">{employee.role}</TableCell>
                    <TableCell className="text-right text-sm">
                      {employee.validUnits}/{employee.units}
                    </TableCell>
                    <TableCell className="text-center">
                      <Badge
                        className={
                          employee.complianceScore >= 90
                            ? "bg-green-100 text-green-700"
                            : employee.complianceScore >= 75
                            ? "bg-yellow-100 text-yellow-700"
                            : "bg-red-100 text-red-700"
                        }
                      >
                        {employee.complianceScore}%
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right">{formatCurrency(employee.basePay)}</TableCell>
                    <TableCell className="text-right">{formatCurrency(employee.incentive)}</TableCell>
                    <TableCell className="text-right font-semibold">
                      {formatCurrency(employee.totalPay)}
                    </TableCell>
                    <TableCell className="text-center">
                      <Button variant="ghost" size="sm" onClick={() => handleViewDetails(employee)}>
                        <Eye className="w-4 h-4" />
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      )}

      {/* Admin View: Same as HR but with Approve/Reject */}
      {viewMode === "admin" && (
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle className="text-base">Employee Payroll Details</CardTitle>
              {snapshot.status === "pending_admin" && (
                <div className="flex gap-2">
                  <Button variant="outline" onClick={() => setShowRejectDialog(true)}>
                    <XCircle className="w-4 h-4 mr-2" />
                    Reject
                  </Button>
                  <Button onClick={handleApprove}>
                    <CheckCircle className="w-4 h-4 mr-2" />
                    Approve
                  </Button>
                </div>
              )}
            </div>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Employee</TableHead>
                  <TableHead>Role</TableHead>
                  <TableHead className="text-right">Units</TableHead>
                  <TableHead className="text-center">Compliance</TableHead>
                  <TableHead className="text-right">Base Pay</TableHead>
                  <TableHead className="text-right">Incentive</TableHead>
                  <TableHead className="text-right">Total Pay</TableHead>
                  <TableHead className="text-center">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {snapshot.employees.map((employee) => (
                  <TableRow key={employee.snapshotId}>
                    <TableCell>
                      <div className="font-medium">{employee.employeeName}</div>
                      <div className="text-xs text-gray-500">{employee.employeeId}</div>
                    </TableCell>
                    <TableCell className="text-sm">{employee.role}</TableCell>
                    <TableCell className="text-right text-sm">
                      {employee.validUnits}/{employee.units}
                    </TableCell>
                    <TableCell className="text-center">
                      <Badge
                        className={
                          employee.complianceScore >= 90
                            ? "bg-green-100 text-green-700"
                            : employee.complianceScore >= 75
                            ? "bg-yellow-100 text-yellow-700"
                            : "bg-red-100 text-red-700"
                        }
                      >
                        {employee.complianceScore}%
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right">{formatCurrency(employee.basePay)}</TableCell>
                    <TableCell className="text-right">{formatCurrency(employee.incentive)}</TableCell>
                    <TableCell className="text-right font-semibold">
                      {formatCurrency(employee.totalPay)}
                    </TableCell>
                    <TableCell className="text-center">
                      <Button variant="ghost" size="sm" onClick={() => handleViewDetails(employee)}>
                        <Eye className="w-4 h-4" />
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      )}

      {/* Accounts View: Limited Data */}
      {viewMode === "accounts" && (
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Payment Processing</CardTitle>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Employee Name</TableHead>
                  <TableHead>Bank Details</TableHead>
                  <TableHead className="text-right">Total Pay</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {snapshot.employees.map((employee) => (
                  <TableRow key={employee.snapshotId}>
                    <TableCell>
                      <div className="font-medium">{employee.employeeName}</div>
                      <div className="text-xs text-gray-500">{employee.employeeId}</div>
                    </TableCell>
                    <TableCell>
                      {employee.bankName && employee.accountNumber ? (
                        <div className="text-sm">
                          <div>{employee.bankName}</div>
                          <div className="text-xs text-gray-500">
                            {employee.accountNumber} • {employee.ifscCode}
                          </div>
                        </div>
                      ) : (
                        <Badge variant="outline" className="bg-red-50 text-red-700">
                          <AlertCircle className="w-3 h-3 mr-1" />
                          Missing Bank Details
                        </Badge>
                      )}
                    </TableCell>
                    <TableCell className="text-right font-semibold text-lg">
                      {formatCurrency(employee.totalPay)}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      )}

      {/* Detail Dialog */}
      <Dialog open={showDetailDialog} onOpenChange={setShowDetailDialog}>
        <DialogContent className="w-[95vw] sm:w-full max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Payroll Snapshot Details</DialogTitle>
            <DialogDescription>
              {selectedEmployee?.employeeName} ({selectedEmployee?.employeeId})
            </DialogDescription>
          </DialogHeader>

          {selectedEmployee && (
            <div className="space-y-4">
              {/* Snapshot Label */}
              <div className="flex items-center gap-3 p-3 bg-blue-50 border border-blue-200 rounded-lg">
                <Database className="w-4 h-4 text-blue-600" />
                <div className="flex-1">
                  <p className="text-xs font-medium text-blue-900">
                    Snapshot Data (Generated: {selectedEmployee.generatedAt})
                  </p>
                </div>
              </div>

              {/* Breakdown */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Card>
                  <CardContent className="p-4">
                    <div className="text-xs text-gray-600 mb-1">Base Pay</div>
                    <div className="text-2xl font-bold text-gray-900">
                      {formatCurrency(selectedEmployee.basePay)}
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardContent className="p-4">
                    <div className="text-xs text-gray-600 mb-1">Incentive</div>
                    <div className="text-2xl font-bold text-green-700">
                      +{formatCurrency(selectedEmployee.incentive)}
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardContent className="p-4">
                    <div className="text-xs text-gray-600 mb-1">Compliance Adjustment</div>
                    <div className="text-2xl font-bold text-orange-700">
                      {selectedEmployee.complianceAdjustment >= 0 ? "+" : ""}
                      {formatCurrency(Math.abs(selectedEmployee.complianceAdjustment))}
                    </div>
                  </CardContent>
                </Card>

                <Card className="border-2 border-blue-500">
                  <CardContent className="p-4">
                    <div className="text-xs text-gray-600 mb-1">Total Pay</div>
                    <div className="text-2xl font-bold text-blue-700">
                      {formatCurrency(selectedEmployee.totalPay)}
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Reject Dialog */}
      <Dialog open={showRejectDialog} onOpenChange={setShowRejectDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Reject Payroll Snapshot</DialogTitle>
            <DialogDescription>
              Please provide a reason for rejecting this payroll snapshot.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Rejection Reason</label>
              <textarea
                className="w-full p-3 border rounded-lg"
                rows={4}
                value={rejectionReason}
                onChange={(e) => setRejectionReason(e.target.value)}
                placeholder="Enter reason for rejection..."
              />
            </div>

            <div className="flex justify-end gap-2">
              <Button variant="outline" onClick={() => setShowRejectDialog(false)}>
                Cancel
              </Button>
              <Button variant="destructive" onClick={handleReject}>
                <XCircle className="w-4 h-4 mr-2" />
                Reject Payroll
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
