/**
 * City Manager Type Definitions
 * P&L Control System - Strategic Decision Layer
 * 
 * Philosophy:
 * - City Manager = CEO of city business
 * - Works ONLY through Cluster Managers
 * - Revenue + EBITDA + Retention + Expansion ownership
 * - NOT an operations interface
 */

// ============================================
// CITY KPI TYPES
// ============================================

export interface CityKPIs {
  revenue: {
    mtd: number;
    target: number;
    percentage: number;
    trend: "UP" | "DOWN" | "STABLE";
    growth: number; // Percentage growth vs last month
  };
  ebitda: {
    percentage: number;
    target: number;
    trend: "UP" | "DOWN" | "STABLE";
    amount: number;
  };
  retention: {
    percentage: number;
    target: number;
    trend: "UP" | "DOWN" | "STABLE";
    churnRate: number;
  };
  units: {
    today: number;
    todayTarget: number;
    mtd: number;
    mtdTarget: number;
  };
  activeCustomers: {
    total: number;
    growth: number; // Month-over-month
    highValue: number;
  };
  attendance: {
    clusterManagers: {
      present: number;
      expected: number;
      percentage: number;
    };
    operationsManagers: {
      present: number;
      expected: number;
      percentage: number;
    };
    supervisors: {
      present: number;
      expected: number;
      percentage: number;
    };
    washers: {
      present: number;
      expected: number;
      percentage: number;
    };
  };
}

// ============================================
// CLUSTER TYPES
// ============================================

export interface ClusterCard {
  id: string;
  clusterName: string;
  cmName: string;
  cmPhoto?: string;
  pincodeDetails?: Array<{
    pincodeId: string;
    pincode: string;
    areaName: string;
  }>;
  revenue: {
    mtd: number;
    target: number;
    percentage: number;
  };
  ebitda: {
    percentage: number;
    contribution: number; // Contribution to city EBITDA
  };
  retention: {
    percentage: number;
    customersAtRisk: number;
  };
  unitProductivity: {
    avgPerOM: number;
    total: number;
  };
  status: "GREEN" | "AMBER" | "RED";
  omCount: number;
  teamCount: number; // ✅ UPDATED: Changed from supervisorCount to teamCount
  washerCount: number;
  activeAlerts: number;
}

export interface ClusterPerformanceDetail {
  cluster: ClusterCard;
  kpiBreakdown: {
    revenue: {
      mtd: number;
      target: number;
      percentage: number;
      trend7Days: number[];
      trend30Days: number[];
    };
    ebitda: {
      percentage: number;
      amount: number;
      trend7Days: number[];
    };
    retention: {
      percentage: number;
      churnedThisMonth: number;
      activeCustomers: number;
    };
    conversion: {
      rate: number;
      target: number;
    };
    compliance: {
      score: number;
      issues: number;
    };
  };
  omDistribution: {
    total: number;
    green: number;
    amber: number;
    red: number;
  };
  interventionHistory: ClusterIntervention[];
}

// ============================================
// INTERVENTION TYPES (CLUSTER GOVERNANCE)
// ============================================

export type ClusterIssueType =
  | "REVENUE_DROP"
  | "EBITDA_DROP"
  | "RETENTION_FAILURE"
  | "MULTI_OM_FAILURE"
  | "COST_SPIKE"
  | "COMPLIANCE_BREACH"
  | "CUSTOMER_ESCALATION";

export type InterventionSeverity = "CRITICAL" | "HIGH" | "MEDIUM";

export type InterventionStatus =
  | "OPEN"
  | "IN_PROGRESS"
  | "CM_ACTION_PENDING"
  | "MONITORING"
  | "ESCALATED_TO_MD"
  | "ESCALATED_TO_HR"
  | "RESOLVED";

export interface ClusterIntervention {
  id: string;
  clusterId: string;
  clusterName: string;
  cmName: string;
  issueType: ClusterIssueType;
  severity: InterventionSeverity;
  status: InterventionStatus;
  triggeredAt: Date;
  daysSinceTrigger: number;
  problemSummary: string;
  autoGeneratedAnalysis: {
    rootCause: string;
    impactMetrics: {
      revenueImpact?: number;
      ebitdaImpact?: number;
      customersAffected?: number;
    };
    trendAnalysis: string;
  };
  cmActionsHistory: {
    timestamp: Date;
    action: string;
    takenBy: string;
    outcome?: string;
  }[];
  cityManagerActions: {
    strategicPlan?: string;
    deadline?: Date;
    assignedTo?: string;
    followUpScheduled?: Date;
  };
  escalation?: {
    escalatedTo: "MD" | "HR" | "BOARD";
    reason: string;
    escalatedAt: Date;
    escalatedBy: string;
  };
  resolvedAt?: Date;
  auditLog: {
    createdBy: string;
    createdAt: Date;
    lastModifiedBy: string;
    lastModifiedAt: Date;
  };
}

// ============================================
// REVENUE & EBITDA TYPES
// ============================================

export interface RevenueEBITDADashboard {
  revenue: {
    total: number;
    target: number;
    percentage: number;
    clusterContributions: {
      clusterName: string;
      amount: number;
      percentage: number;
    }[];
    unitEconomics: {
      totalUnits: number;
      avgPricePerUnit: number;
      revenue: number;
    };
    trend: {
      month: string;
      amount: number;
    }[];
  };
  ebitda: {
    percentage: number;
    amount: number;
    target: number;
    costBreakdown: {
      washerCost: number;
      supervisorCost: number;
      consumables: number;
      operationalOverhead: number;
      marketing: number;
      other: number;
    };
    trend: {
      month: string;
      percentage: number;
    }[];
  };
  insights: {
    revenueGrowthTrend: "ACCELERATING" | "STABLE" | "DECLINING";
    costSpikeAlerts: {
      category: string;
      increase: number;
      threshold: number;
    }[];
    profitabilityWarnings: string[];
  };
}

// ============================================
// RETENTION & CUSTOMER HEALTH TYPES
// ============================================

export interface RetentionCustomerHealth {
  retention90Day: {
    percentage: number;
    target: number;
    trend: "UP" | "DOWN" | "STABLE";
  };
  churnTrend: {
    month: string;
    churnRate: number;
    customersLost: number;
  }[];
  clusterRetentionComparison: {
    clusterName: string;
    retentionRate: number;
    customersAtRisk: number;
  }[];
  highRiskSegments: {
    segment: string;
    customersCount: number;
    churnRisk: "HIGH" | "MEDIUM" | "LOW";
    reasons: string[];
  }[];
  rootCausePatterns: {
    pricing: number;
    quality: number;
    service: number;
    competition: number;
  };
  retentionActions: {
    suggested: string[];
    inProgress: number;
    completed: number;
  };
}

// ============================================
// EXPANSION & TERRITORY TYPES
// ============================================

export interface Territory {
  id: string;
  name: string;
  status: "ACTIVE" | "UNCOVERED" | "PROPOSED" | "PLANNING";
  coverage: number; // Percentage
  potentialCustomers: number;
  estimatedRevenue: number;
  requiredInvestment?: number;
}

export interface ExpansionPlanning {
  cityOverview: {
    totalTerritories: number;
    activeTerritories: number;
    coveragePercentage: number;
  };
  territories: Territory[];
  proposedExpansionZones: {
    id: string;
    name: string;
    priority: "HIGH" | "MEDIUM" | "LOW";
    potentialRevenue: number;
    investmentRequired: number;
    timelineMonths: number;
    status: "PROPOSED" | "APPROVED" | "PLANNING" | "IN_PROGRESS";
  }[];
  clusterPipeline: {
    proposedClusters: number;
    approvalPending: number;
    inSetup: number;
  };
  infrastructureRequirements: {
    item: string;
    quantity: number;
    estimatedCost: number;
    priority: "HIGH" | "MEDIUM" | "LOW";
  }[];
}

// ============================================
// ALERTS & ESCALATIONS TYPES
// ============================================

export type CityAlertType =
  | "CLUSTER_REVENUE_CRITICAL"
  | "EBITDA_DROP"
  | "MULTI_CLUSTER_FAILURE"
  | "LEGAL_RISK"
  | "BRAND_RISK"
  | "MASS_SERVICE_FAILURE"
  | "RETENTION_CRISIS"
  | "COST_ANOMALY";

export type AlertPriority = "CRITICAL" | "WARNING" | "INFO";

export interface CityAlert {
  id: string;
  type: CityAlertType;
  priority: AlertPriority;
  title: string;
  description: string;
  impact: string;
  affectedClusters: string[];
  timeElapsed: number; // minutes
  createdAt: Date;
  autoEscalateIn?: number; // minutes
  actions: {
    escalateToMD?: boolean;
    initiateIntervention?: boolean;
    requiresDecision?: boolean;
  };
  decisionLog?: {
    decision: string;
    takenBy: string;
    takenAt: Date;
  };
}

// ============================================
// INCENTIVE TRACKER TYPES
// ============================================

export interface CityManagerIncentive {
  month: string;
  kpiScoring: {
    revenue: {
      weightage: number;
      achievement: number;
      score: number;
    };
    ebitda: {
      weightage: number;
      achievement: number;
      score: number;
      mandatoryThreshold: number;
      thresholdMet: boolean;
    };
    retention: {
      weightage: number;
      achievement: number;
      score: number;
    };
    growth: {
      weightage: number;
      achievement: number;
      score: number;
    };
  };
  incentiveForecast: {
    baseIncentive: number;
    kpiBonus: number;
    growthBonus: number;
    totalProjected: number;
  };
  lastMonthPayout: number;
  trend: "UP" | "DOWN" | "STABLE";
  auditLog: {
    systemGenerated: boolean;
    lastRecalculated: Date;
  };
}

// ============================================
// REPORTS & ANALYTICS TYPES
// ============================================

export interface CityReport {
  id: string;
  reportType: "MONTHLY_P&L" | "CLUSTER_PERFORMANCE" | "RETENTION_ANALYSIS" | "EXPANSION_FEASIBILITY";
  month: string;
  generatedAt: Date;
  generatedBy: string;
  summary: string;
  downloadUrl?: string;
}

// ============================================
// MANAGEMENT VISIBILITY (AUDIT) TYPES
// ============================================

export interface CityAuditLog {
  id: string;
  timestamp: Date;
  action: string;
  performedBy: string;
  affectedEntity: string;
  entityType: "CLUSTER" | "INTERVENTION" | "EXPANSION" | "FINANCIAL_DECISION";
  details: string;
  visibleToMD: boolean;
  visibleToBoard: boolean;
}
