// Revenue Data - Synchronized with CleanCar 360° Doorstep Service Model
// March 2026 data aligned with washer performance and subscriptions

export interface RevenueEntry {
  id: string;
  invoiceNumber: string;
  customerName: string;
  customerId: string;
  packageType: string; // Basic, Premium, Elite, Elite Plus
  subscriptionType: string; // Weekly, Monthly, Quarterly
  washerId: string;
  washerName: string;
  pinCode: string;
  invoiceDate: string;
  washDate: string;
  washNumber: number; // Which wash in the subscription period
  amount: number; // Base package amount
  cgst: number;
  sgst: number;
  igst?: number; // For inter-state transactions (optional)
  totalAmount: number;
  paymentMode: string;
  paymentStatus: string;
  transactionId: string;
  revenueAccount: string;
  autoGenerated: boolean;
  syncedToAccounts: boolean;
  jobReference: string;
}

// March 2026 Revenue Data - Doorstep Car Washing Service
export const REVENUE_DATA_MARCH_2026: RevenueEntry[] = [
  // Suresh Kumar's jobs (477 total in March)
  {
    id: "REV-MAR-001",
    invoiceNumber: "INV-2026-03-001",
    customerName: "Rajesh Patel",
    customerId: "CUST-395005-001",
    packageType: "Premium",
    subscriptionType: "Monthly",
    washerId: "washer-001",
    washerName: "Suresh Kumar",
    pinCode: "395005",
    invoiceDate: "2026-03-01",
    washDate: "2026-03-01",
    washNumber: 1,
    amount: 1200,
    cgst: 108,
    sgst: 108,
    totalAmount: 1416,
    paymentMode: "UPI",
    paymentStatus: "Received",
    transactionId: "UPI202603011234",
    revenueAccount: "4100 - Subscription Revenue - Premium",
    autoGenerated: true,
    syncedToAccounts: true,
    jobReference: "JOB-2026-03-01-001",
  },
  {
    id: "REV-MAR-002",
    invoiceNumber: "INV-2026-03-002",
    customerName: "Sneha Desai",
    customerId: "CUST-395005-012",
    packageType: "Basic",
    subscriptionType: "Weekly",
    washerId: "washer-001",
    washerName: "Suresh Kumar",
    pinCode: "395005",
    invoiceDate: "2026-03-01",
    washDate: "2026-03-01",
    washNumber: 1,
    amount: 400,
    cgst: 36,
    sgst: 36,
    totalAmount: 472,
    paymentMode: "UPI",
    paymentStatus: "Received",
    transactionId: "UPI202603011567",
    revenueAccount: "4100 - Subscription Revenue - Basic",
    autoGenerated: true,
    syncedToAccounts: true,
    jobReference: "JOB-2026-03-01-008",
  },
  {
    id: "REV-MAR-003",
    invoiceNumber: "INV-2026-03-003",
    customerName: "Vijay Shah",
    customerId: "CUST-395005-025",
    packageType: "Elite",
    subscriptionType: "Monthly",
    washerId: "washer-001",
    washerName: "Suresh Kumar",
    pinCode: "395005",
    invoiceDate: "2026-03-02",
    washDate: "2026-03-02",
    washNumber: 2,
    amount: 2000,
    cgst: 180,
    sgst: 180,
    totalAmount: 2360,
    paymentMode: "Credit Card",
    paymentStatus: "Received",
    transactionId: "CC202603028765",
    revenueAccount: "4100 - Subscription Revenue - Elite",
    autoGenerated: true,
    syncedToAccounts: true,
    jobReference: "JOB-2026-03-02-015",
  },
  {
    id: "REV-MAR-004",
    invoiceNumber: "INV-2026-03-004",
    customerName: "Meera Kulkarni",
    customerId: "CUST-395005-033",
    packageType: "Premium",
    subscriptionType: "Quarterly",
    washerId: "washer-001",
    washerName: "Suresh Kumar",
    pinCode: "395005",
    invoiceDate: "2026-03-03",
    washDate: "2026-03-03",
    washNumber: 3,
    amount: 3200,
    cgst: 288,
    sgst: 288,
    totalAmount: 3776,
    paymentMode: "Bank Transfer",
    paymentStatus: "Received",
    transactionId: "NEFT202603034521",
    revenueAccount: "4100 - Subscription Revenue - Premium",
    autoGenerated: true,
    syncedToAccounts: true,
    jobReference: "JOB-2026-03-03-022",
  },
  
  // Ramesh K.'s jobs (532 total in March)
  {
    id: "REV-MAR-005",
    invoiceNumber: "INV-2026-03-005",
    customerName: "Anil Verma",
    customerId: "CUST-395001-008",
    packageType: "Elite Plus",
    subscriptionType: "Monthly",
    washerId: "washer-002",
    washerName: "Ramesh K.",
    pinCode: "395001",
    invoiceDate: "2026-03-01",
    washDate: "2026-03-01",
    washNumber: 1,
    amount: 2800,
    cgst: 252,
    sgst: 252,
    totalAmount: 3304,
    paymentMode: "UPI",
    paymentStatus: "Received",
    transactionId: "UPI202603019876",
    revenueAccount: "4100 - Subscription Revenue - Elite Plus",
    autoGenerated: true,
    syncedToAccounts: true,
    jobReference: "JOB-2026-03-01-045",
  },
  {
    id: "REV-MAR-006",
    invoiceNumber: "INV-2026-03-006",
    customerName: "Pooja Mehta",
    customerId: "CUST-395002-014",
    packageType: "Premium",
    subscriptionType: "Monthly",
    washerId: "washer-002",
    washerName: "Ramesh K.",
    pinCode: "395002",
    invoiceDate: "2026-03-01",
    washDate: "2026-03-01",
    washNumber: 1,
    amount: 1200,
    cgst: 108,
    sgst: 108,
    totalAmount: 1416,
    paymentMode: "Wallet",
    paymentStatus: "Received",
    transactionId: "PAYTM202603012345",
    revenueAccount: "4100 - Subscription Revenue - Premium",
    autoGenerated: true,
    syncedToAccounts: true,
    jobReference: "JOB-2026-03-01-052",
  },
  
  // Mahesh S.'s jobs (498 total in March)
  {
    id: "REV-MAR-007",
    invoiceNumber: "INV-2026-03-007",
    customerName: "Karthik Iyer",
    customerId: "CUST-395004-021",
    packageType: "Elite",
    subscriptionType: "Monthly",
    washerId: "washer-003",
    washerName: "Mahesh S.",
    pinCode: "395004",
    invoiceDate: "2026-03-02",
    washDate: "2026-03-02",
    washNumber: 2,
    amount: 2000,
    cgst: 180,
    sgst: 180,
    totalAmount: 2360,
    paymentMode: "UPI",
    paymentStatus: "Received",
    transactionId: "UPI202603025432",
    revenueAccount: "4100 - Subscription Revenue - Elite",
    autoGenerated: true,
    syncedToAccounts: true,
    jobReference: "JOB-2026-03-02-078",
  },
  {
    id: "REV-MAR-008",
    invoiceNumber: "INV-2026-03-008",
    customerName: "Divya Nair",
    customerId: "CUST-395005-042",
    packageType: "Elite Plus",
    subscriptionType: "Quarterly",
    washerId: "washer-003",
    washerName: "Mahesh S.",
    pinCode: "395005",
    invoiceDate: "2026-03-02",
    washDate: "2026-03-02",
    washNumber: 2,
    amount: 7500,
    cgst: 675,
    sgst: 675,
    totalAmount: 8850,
    paymentMode: "Credit Card",
    paymentStatus: "Received",
    transactionId: "CC202603026789",
    revenueAccount: "4100 - Subscription Revenue - Elite Plus",
    autoGenerated: true,
    syncedToAccounts: true,
    jobReference: "JOB-2026-03-02-085",
  },
  
  // Dinesh P.'s jobs (445 total in March)
  {
    id: "REV-MAR-009",
    invoiceNumber: "INV-2026-03-009",
    customerName: "Sunil Gupta",
    customerId: "CUST-395003-016",
    packageType: "Basic",
    subscriptionType: "Weekly",
    washerId: "washer-004",
    washerName: "Dinesh P.",
    pinCode: "395003",
    invoiceDate: "2026-03-03",
    washDate: "2026-03-03",
    washNumber: 1,
    amount: 400,
    cgst: 36,
    sgst: 36,
    totalAmount: 472,
    paymentMode: "UPI",
    paymentStatus: "Received",
    transactionId: "UPI202603033456",
    revenueAccount: "4100 - Subscription Revenue - Basic",
    autoGenerated: true,
    syncedToAccounts: true,
    jobReference: "JOB-2026-03-03-092",
  },
  {
    id: "REV-MAR-010",
    invoiceNumber: "INV-2026-03-010",
    customerName: "Lakshmi Reddy",
    customerId: "CUST-395003-028",
    packageType: "Premium",
    subscriptionType: "Monthly",
    washerId: "washer-004",
    washerName: "Dinesh P.",
    pinCode: "395003",
    invoiceDate: "2026-03-03",
    washDate: "2026-03-03",
    washNumber: 3,
    amount: 1200,
    cgst: 108,
    sgst: 108,
    totalAmount: 1416,
    paymentMode: "UPI",
    paymentStatus: "Pending",
    transactionId: "UPI202603037654",
    revenueAccount: "4100 - Subscription Revenue - Premium",
    autoGenerated: true,
    syncedToAccounts: false,
    jobReference: "JOB-2026-03-03-098",
  },
  
  // Kiran M.'s jobs (512 total in March)
  {
    id: "REV-MAR-011",
    invoiceNumber: "INV-2026-03-011",
    customerName: "Harish Joshi",
    customerId: "CUST-395006-005",
    packageType: "Elite",
    subscriptionType: "Monthly",
    washerId: "washer-005",
    washerName: "Kiran M.",
    pinCode: "395006",
    invoiceDate: "2026-03-04",
    washDate: "2026-03-04",
    washNumber: 1,
    amount: 2000,
    cgst: 180,
    sgst: 180,
    totalAmount: 2360,
    paymentMode: "Credit Card",
    paymentStatus: "Received",
    transactionId: "CC202603048901",
    revenueAccount: "4100 - Subscription Revenue - Elite",
    autoGenerated: true,
    syncedToAccounts: true,
    jobReference: "JOB-2026-03-04-112",
  },
  {
    id: "REV-MAR-012",
    invoiceNumber: "INV-2026-03-012",
    customerName: "Neha Kapoor",
    customerId: "CUST-395006-019",
    packageType: "Premium",
    subscriptionType: "Weekly",
    washerId: "washer-005",
    washerName: "Kiran M.",
    pinCode: "395006",
    invoiceDate: "2026-03-04",
    washDate: "2026-03-04",
    washNumber: 1,
    amount: 550,
    cgst: 49.5,
    sgst: 49.5,
    totalAmount: 649,
    paymentMode: "UPI",
    paymentStatus: "Received",
    transactionId: "UPI202603042345",
    revenueAccount: "4100 - Subscription Revenue - Premium",
    autoGenerated: true,
    syncedToAccounts: true,
    jobReference: "JOB-2026-03-04-118",
  },
];

// Revenue aggregation by package
export function getRevenueByPackage() {
  const packageRevenue = {
    Basic: { count: 0, revenue: 0 },
    Premium: { count: 0, revenue: 0 },
    Elite: { count: 0, revenue: 0 },
    "Elite Plus": { count: 0, revenue: 0 },
  };
  
  REVENUE_DATA_MARCH_2026.forEach((entry) => {
    const pkg = entry.packageType as keyof typeof packageRevenue;
    if (packageRevenue[pkg]) {
      packageRevenue[pkg].count += 1;
      packageRevenue[pkg].revenue += entry.totalAmount;
    }
  });
  
  return Object.entries(packageRevenue).map(([name, data]) => ({
    id: name.toLowerCase().replace(" ", "-"),
    name,
    count: data.count,
    revenue: data.revenue,
  }));
}

// Revenue aggregation by washer
export function getRevenueByWasher() {
  const washerRevenue: Record<string, { name: string; count: number; revenue: number }> = {};
  
  REVENUE_DATA_MARCH_2026.forEach((entry) => {
    if (!washerRevenue[entry.washerId]) {
      washerRevenue[entry.washerId] = {
        name: entry.washerName,
        count: 0,
        revenue: 0,
      };
    }
    washerRevenue[entry.washerId].count += 1;
    washerRevenue[entry.washerId].revenue += entry.totalAmount;
  });
  
  return Object.entries(washerRevenue).map(([id, data]) => ({
    id,
    ...data,
  }));
}

// Revenue aggregation by payment mode
export function getRevenueByPaymentMode() {
  const paymentRevenue: Record<string, number> = {};
  
  REVENUE_DATA_MARCH_2026.forEach((entry) => {
    if (!paymentRevenue[entry.paymentMode]) {
      paymentRevenue[entry.paymentMode] = 0;
    }
    paymentRevenue[entry.paymentMode] += entry.totalAmount;
  });
  
  return Object.entries(paymentRevenue).map(([mode, revenue]) => ({
    id: mode.toLowerCase().replace(" ", "-"),
    mode,
    revenue,
  }));
}

// Total revenue summary
export function getRevenueSummary() {
  const totalRevenue = REVENUE_DATA_MARCH_2026.reduce((sum, entry) => sum + entry.totalAmount, 0);
  const receivedRevenue = REVENUE_DATA_MARCH_2026.filter(e => e.paymentStatus === "Received").reduce((sum, entry) => sum + entry.totalAmount, 0);
  const pendingRevenue = REVENUE_DATA_MARCH_2026.filter(e => e.paymentStatus === "Pending").reduce((sum, entry) => sum + entry.totalAmount, 0);
  
  return {
    totalRevenue,
    receivedRevenue,
    pendingRevenue,
    totalEntries: REVENUE_DATA_MARCH_2026.length,
    receivedCount: REVENUE_DATA_MARCH_2026.filter(e => e.paymentStatus === "Received").length,
    pendingCount: REVENUE_DATA_MARCH_2026.filter(e => e.paymentStatus === "Pending").length,
  };
}