/**
 * Permission Matrix Configuration (MC-11)
 *
 * Defines permissions by City + Role
 * Supports city-specific governance rules
 *
 * STRUCTURE: City → Role → Module → Actions
 */

import type { Role } from "../lib/roleConfig";
import type { City, PermissionMatrix } from "../types/permissions";

// Type for city-specific role permissions
type RolePermissions = {
  [role in Role]: PermissionMatrix;
};

/**
 * PERMISSION MATRIX
 *
 * City-scoped permission definitions
 * Each city can have different governance rules
 */
export const permissionMatrix: Record<City, RolePermissions> = {
  "CITY-SURAT": {
    "Super Admin": {
      dashboard: ["view", "create", "edit", "delete", "export", "audit"],
      users: ["view", "create", "edit", "delete", "export"],
      leads: ["view", "create", "edit", "delete", "export"],
      customers: ["view", "create", "edit", "delete", "export"],
      "car-washer": ["view", "create", "edit", "delete", "export"],
      supervisor: ["view", "create", "edit", "delete", "export"],
      operations: ["view", "create", "edit", "delete", "approve", "export"],
      complaints: ["view", "create", "edit", "delete", "approve", "export"],
      inventory: ["view", "create", "edit", "delete", "approve", "export"],
      store: ["view", "create", "edit", "delete", "approve", "export"],
      procurement: ["view", "create", "edit", "delete", "approve", "export"],
      "cloth-tracking": ["view", "create", "edit", "delete", "export"],
      advance: ["view", "create", "edit", "delete", "approve", "export"],
      finance: ["view", "create", "edit", "delete", "approve", "export", "audit"],
      hr: ["view", "create", "edit", "delete", "approve", "export"],
      travel: ["view", "create"],
      leave: ["view", "create", "approve", "export"],
      approvals: ["view", "approve", "export"],
      "audit-trail": ["view", "export", "audit"],
      performance: ["view", "create", "edit", "export"],
      analytics: ["view", "export"],
      payroll: ["view", "create", "edit", "approve", "export"],
      reports: ["view", "export"],
      accounts: ["view", "create", "edit", "approve", "export"],
      "store-manager": ["view", "create", "edit", "approve", "export"],
      "crm": ["view", "create", "edit", "delete", "export"],
      "jobs": ["view", "create", "edit", "delete", "approve", "export"],
      "admin": ["view", "create", "edit", "delete", "export", "audit"],
      "payroll-self-service": ["view"],
    },

    Admin: {
      dashboard: ["view", "create", "edit", "export"],
      users: ["view", "create", "edit", "export"],
      leads: ["view", "create", "edit", "export"],
      customers: ["view", "create", "edit", "export"],
      "car-washer": ["view", "create", "edit", "export"],
      supervisor: ["view", "create", "edit", "export"],
      operations: ["view", "create", "edit", "approve", "export"],
      complaints: ["view", "create", "edit", "approve", "export"],
      inventory: ["view", "create", "edit", "approve", "export"],
      store: ["view", "create", "edit", "approve", "export"],
      procurement: ["view", "create", "edit", "approve", "export"],
      "cloth-tracking": ["view", "create", "edit", "export"],
      finance: ["view", "create", "edit", "approve", "export"],
      hr: ["view", "create", "edit", "approve", "export"],
      travel: ["view", "create"],
      leave: ["view", "create", "approve", "export"],
      approvals: ["view", "approve", "export"],
      "audit-trail": ["view", "export"],
      performance: ["view", "create", "edit", "export"],
      analytics: ["view", "export"],
      payroll: ["view", "create", "edit", "approve", "export"],
      reports: ["view", "export"],
      accounts: ["view", "create", "edit", "export"],
      "store-manager": ["view", "create", "edit", "export"],
      "crm": ["view", "create", "edit", "export"],
      "jobs": ["view", "create", "edit", "approve", "export"],
      "admin": ["view", "create", "edit", "export"],
      "payroll-self-service": ["view"],
    },

    "City Manager": {
      dashboard: ["view", "export"],
      users: ["view", "export"],
      leads: ["view", "create", "edit", "export"],
      customers: ["view", "create", "edit", "export"],
      operations: ["view", "create", "edit", "export"],
      complaints: ["view", "create", "edit", "approve", "export"],
      finance: ["view", "export"],
      travel: ["view", "create"],
      leave: ["view", "approve", "export"],
      performance: ["view", "export"],
      analytics: ["view", "export"],
      reports: ["view", "export"],
      "crm": ["view", "create", "edit", "export"],
      "jobs": ["view", "export"],
      "admin": [],
      "audit-trail": ["view", "export"],
      "cloth-tracking": ["view"],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    "Cluster Manager": {
      dashboard: ["view", "export"],
      users: ["view"],
      leads: ["view", "create", "edit", "export"],
      customers: ["view", "create", "edit", "export"],
      operations: ["view", "create", "edit", "export"],
      complaints: ["view", "create", "edit", "approve"],
      finance: ["view"],
      travel: ["view", "create"],
      leave: ["view", "approve"],
      performance: ["view", "export"],
      analytics: ["view"],
      reports: ["view"],
      "crm": ["view", "create", "edit"],
      "jobs": ["view"],
      "admin": [],
      "audit-trail": ["view"],
      "cloth-tracking": ["view"],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    "Sr Operations Manager": {
      dashboard: ["view", "export"],
      "car-washer": ["view", "create", "edit", "export"],
      supervisor: ["view", "create", "edit", "export"],
      operations: ["view", "create", "edit", "approve", "export"],
      complaints: ["view", "create", "edit", "approve", "export"],
      travel: ["view", "create"],
      leave: ["view", "approve", "export"],
      approvals: ["view", "approve"],
      performance: ["view", "export"],
      analytics: ["view"],
      "jobs": ["view", "create", "edit", "approve", "export"],
      "crm": [],
      "admin": [],
      "audit-trail": ["view"],
      "cloth-tracking": ["view", "create"],
      "store-manager": ["view"],
      "payroll-self-service": ["view"],
    },

    "Operations Manager": {
      dashboard: ["view", "export"],
      "car-washer": ["view", "create", "edit", "export"],
      supervisor: ["view", "create", "edit", "export"],
      operations: ["view", "create", "edit", "approve"],
      complaints: ["view", "create", "edit", "approve"],
      travel: ["view", "create"],
      leave: ["view", "approve"],
      approvals: ["view", "approve"],
      performance: ["view"],
      "jobs": ["view", "create", "edit", "approve"],
      "crm": [],
      "admin": [],
      "audit-trail": ["view"],
      "cloth-tracking": ["view", "create"],
      "store-manager": ["view"],
      "payroll-self-service": ["view"],
    },

    Supervisor: {
      dashboard: ["view"],
      "car-washer": ["view", "create", "edit"],
      supervisor: ["view"],
      complaints: ["view", "create"],
      inventory: ["view"],
      "cloth-tracking": ["view", "create", "edit"],
      advance: ["view", "create"],
      travel: ["view", "create"],
      leave: ["view", "create", "approve"],
      performance: ["view"],
      "jobs": ["view", "create"],
      "crm": [],
      "admin": [],
      "audit-trail": [],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    "Car Washer": {
      dashboard: ["view"],
      "car-washer": ["view", "create"],
      "cloth-tracking": ["view"],
      advance: ["view", "create"],
      travel: ["view", "create"],
      leave: ["view", "create"],
      performance: ["view"],
      "jobs": ["view", "create"],
      "crm": [],
      "admin": [],
      "audit-trail": [],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    TSM: {
      dashboard: ["view", "export"],
      leads: ["view", "create", "edit", "export"],
      customers: ["view", "create", "edit", "export"],
      complaints: ["view", "create", "edit"],
      travel: ["view", "create"],
      leave: ["view", "create", "approve"],
      performance: ["view", "export"],
      "crm": ["view", "create", "edit", "export"],
      "jobs": [],
      "admin": [],
      "audit-trail": [],
      "cloth-tracking": [],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    TSE: {
      dashboard: ["view"],
      leads: ["view", "create", "edit"],
      customers: ["view", "create", "edit"],
      travel: ["view", "create"],
      leave: ["view", "create"],
      performance: ["view"],
      "crm": ["view", "create", "edit"],
      "jobs": [],
      "admin": [],
      "audit-trail": [],
      "cloth-tracking": [],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    CCE: {
      dashboard: ["view"],
      leads: ["view", "edit"],
      complaints: ["view", "create", "edit"],
      customers: ["view", "edit"],
      travel: ["view", "create"],
      leave: ["view", "create"],
      performance: ["view"],
      "crm": ["view", "create", "edit"],
      "jobs": [],
      "admin": [],
      "audit-trail": [],
      "cloth-tracking": [],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    "Store Manager": {
      dashboard: ["view", "export"],
      inventory: ["view", "create", "edit", "export"],
      store: ["view", "create", "edit", "export"],
      "store-manager": ["view", "create", "edit", "export"],
      "cloth-tracking": ["view", "create", "edit"],
      travel: ["view", "create"],
      leave: ["view", "create"],
      approvals: ["view", "approve"],
      performance: ["view"],
      "crm": [],
      "jobs": ["view"],
      "admin": [],
      "audit-trail": ["view"],
      "payroll-self-service": ["view"],
    },

    "Procurement Manager": {
      dashboard: ["view", "export"],
      procurement: ["view", "create", "edit", "approve", "export"],
      inventory: ["view", "create", "edit"],
      store: ["view", "create", "edit"],
      travel: ["view", "create"],
      leave: ["view", "create"],
      approvals: ["view", "approve"],
      "crm": [],
      "jobs": [],
      "admin": [],
      "audit-trail": ["view"],
      "cloth-tracking": ["view"],
      "store-manager": ["view"],
      "payroll-self-service": ["view"],
    },

    Accounts: {
      dashboard: ["view", "export"],
      finance: ["view", "create", "edit", "export"],
      accounts: ["view", "create", "edit", "export"],
      customers: ["view"],
      travel: ["view", "create"],
      leave: ["view", "create"],
      approvals: ["view", "approve"],
      performance: ["view"],
      payroll: ["view", "create", "edit", "export"],
      advance: ["view"],
      "crm": [],
      "jobs": [],
      "admin": [],
      "audit-trail": ["view", "export"],
      "cloth-tracking": [],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    HR: {
      dashboard: ["view", "export"],
      users: ["view", "create", "edit", "export"],
      hr: ["view", "create", "edit", "approve", "export"],
      advance: ["view", "create", "edit", "approve"],
      travel: ["view", "create"],
      leave: ["view", "create", "approve", "export"],
      approvals: ["view", "approve", "export"],
      performance: ["view", "export"],
      payroll: ["view", "create", "edit", "export"],
      "crm": [],
      "jobs": [],
      "admin": [],
      "audit-trail": ["view", "export"],
      "cloth-tracking": [],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    Manager: {
      dashboard: ["view", "export"],
      users: ["view"],
      leads: ["view", "create", "edit", "export"],
      customers: ["view", "create", "edit", "export"],
      operations: ["view", "create", "edit", "approve"],
      complaints: ["view", "create", "edit", "approve"],
      travel: ["view", "create"],
      leave: ["view", "create", "approve"],
      approvals: ["view", "approve"],
      performance: ["view", "export"],
      analytics: ["view"],
      "crm": ["view", "create", "edit", "export"],
      "jobs": ["view", "create", "edit"],
      "admin": [],
      "audit-trail": ["view"],
      "cloth-tracking": ["view"],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    "Marketing Agency": {
      dashboard: ["view"],
      crm: ["view"],
      leads: ["view"],
      performance: ["view", "export"],
      analytics: ["view", "export"],
      reports: ["view", "export"],
      hr: ["view"],
      // Explicitly NO permissions on sensitive modules:
      finance: [],
      accounts: [],
      payroll: [],
      users: [],
      admin: [],
      "audit-trail": [],
      inventory: [],
      procurement: [],
      advance: [],
      approvals: [],
    },
  },

  "CITY-MUMBAI": {
    // Mumbai can have stricter or different permissions
    // For now, copy Surat permissions (can be customized per city governance)
    "Super Admin": {
      dashboard: ["view", "create", "edit", "delete", "export", "audit"],
      users: ["view", "create", "edit", "delete", "export"],
      leads: ["view", "create", "edit", "delete", "export"],
      customers: ["view", "create", "edit", "delete", "export"],
      "car-washer": ["view", "create", "edit", "delete", "export"],
      supervisor: ["view", "create", "edit", "delete", "export"],
      operations: ["view", "create", "edit", "delete", "approve", "export"],
      complaints: ["view", "create", "edit", "delete", "approve", "export"],
      inventory: ["view", "create", "edit", "delete", "approve", "export"],
      store: ["view", "create", "edit", "delete", "approve", "export"],
      procurement: ["view", "create", "edit", "delete", "approve", "export"],
      "cloth-tracking": ["view", "create", "edit", "delete", "export"],
      advance: ["view", "create", "edit", "delete", "approve", "export"],
      finance: ["view", "create", "edit", "delete", "approve", "export", "audit"],
      hr: ["view", "create", "edit", "delete", "approve", "export"],
      travel: ["view", "create"],
      leave: ["view", "create", "approve", "export"],
      approvals: ["view", "approve", "export"],
      "audit-trail": ["view", "export", "audit"],
      performance: ["view", "create", "edit", "export"],
      analytics: ["view", "export"],
      payroll: ["view", "create", "edit", "approve", "export"],
      reports: ["view", "export"],
      accounts: ["view", "create", "edit", "approve", "export"],
      "store-manager": ["view", "create", "edit", "approve", "export"],
      "crm": ["view", "create", "edit", "delete", "export"],
      "jobs": ["view", "create", "edit", "delete", "approve", "export"],
      "admin": ["view", "create", "edit", "delete", "export", "audit"],
      "payroll-self-service": ["view"],
    },

    Admin: {
      dashboard: ["view", "export"],
      users: ["view", "create", "edit"],
      leads: ["view", "create", "edit", "export"],
      customers: ["view", "create", "edit", "export"],
      "car-washer": ["view", "create", "edit"],
      supervisor: ["view", "create", "edit"],
      operations: ["view", "create", "edit", "approve"],
      complaints: ["view", "create", "edit", "approve"],
      inventory: ["view", "create", "edit", "approve"],
      finance: ["view", "export"], // Mumbai Admin more restricted on finance
      hr: ["view", "create", "edit", "approve"],
      travel: ["view", "create"],
      leave: ["view", "create", "approve"],
      approvals: ["view", "approve"],
      performance: ["view", "export"],
      analytics: ["view"],
      "crm": ["view", "create", "edit", "export"],
      "jobs": ["view", "create", "edit", "approve", "export"],
      "admin": ["view", "create", "edit", "export"],
      "payroll-self-service": ["view"],
    },

    "City Manager": {
      dashboard: ["view", "export"],
      users: ["view"],
      leads: ["view", "create", "edit", "export"],
      customers: ["view", "create", "edit", "export"],
      operations: ["view", "create", "edit"],
      complaints: ["view", "create", "edit", "approve"],
      finance: ["view"],
      travel: ["view", "create"],
      leave: ["view", "approve"],
      performance: ["view", "export"],
      analytics: ["view"],
      "crm": ["view", "create", "edit", "export"],
      "jobs": ["view", "export"],
      "admin": [],
      "audit-trail": ["view", "export"],
      "cloth-tracking": ["view"],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    "Cluster Manager": {
      dashboard: ["view"],
      users: ["view"],
      leads: ["view", "create", "edit"],
      customers: ["view", "create", "edit"],
      operations: ["view", "create", "edit"],
      complaints: ["view", "create", "edit"],
      travel: ["view", "create"],
      leave: ["view", "approve"],
      performance: ["view"],
      "crm": ["view", "create", "edit"],
      "jobs": ["view"],
      "admin": [],
      "audit-trail": ["view"],
      "cloth-tracking": ["view"],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    "Sr Operations Manager": {
      dashboard: ["view"],
      "car-washer": ["view", "create", "edit"],
      supervisor: ["view", "create", "edit"],
      operations: ["view", "create", "edit", "approve"],
      complaints: ["view", "create", "edit", "approve"],
      travel: ["view", "create"],
      leave: ["view", "approve"],
      approvals: ["view", "approve"],
      performance: ["view"],
      "jobs": ["view", "create", "edit", "approve", "export"],
      "crm": [],
      "admin": [],
      "audit-trail": ["view"],
      "cloth-tracking": ["view", "create"],
      "store-manager": ["view"],
      "payroll-self-service": ["view"],
    },

    "Operations Manager": {
      dashboard: ["view"],
      "car-washer": ["view", "create", "edit"],
      supervisor: ["view", "create", "edit"],
      operations: ["view", "create", "edit"],
      complaints: ["view", "create", "edit"],
      travel: ["view", "create"],
      leave: ["view", "approve"],
      performance: ["view"],
      "jobs": ["view", "create", "edit", "approve"],
      "crm": [],
      "admin": [],
      "audit-trail": ["view"],
      "cloth-tracking": ["view", "create"],
      "store-manager": ["view"],
      "payroll-self-service": ["view"],
    },

    Supervisor: {
      dashboard: ["view"],
      "car-washer": ["view", "create"],
      complaints: ["view", "create"],
      inventory: ["view"],
      "cloth-tracking": ["view", "create"],
      travel: ["view", "create"],
      leave: ["view", "create"],
      performance: ["view"],
      "jobs": ["view", "create"],
      "crm": [],
      "admin": [],
      "audit-trail": [],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    "Car Washer": {
      dashboard: ["view"],
      "car-washer": ["view", "create"],
      travel: ["view", "create"],
      leave: ["view", "create"],
      performance: ["view"],
      "jobs": ["view", "create"],
      "crm": [],
      "admin": [],
      "audit-trail": [],
      "cloth-tracking": [],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    TSM: {
      dashboard: ["view"],
      leads: ["view", "create", "edit"],
      customers: ["view", "create", "edit"],
      complaints: ["view", "create"],
      travel: ["view", "create"],
      leave: ["view", "create", "approve"],
      performance: ["view"],
      "crm": ["view", "create", "edit", "export"],
      "jobs": [],
      "admin": [],
      "audit-trail": [],
      "cloth-tracking": [],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    TSE: {
      dashboard: ["view"],
      leads: ["view", "create", "edit"],
      customers: ["view", "create"],
      travel: ["view", "create"],
      leave: ["view", "create"],
      performance: ["view"],
      "crm": ["view", "create", "edit"],
      "jobs": [],
      "admin": [],
      "audit-trail": [],
      "cloth-tracking": [],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    CCE: {
      dashboard: ["view"],
      leads: ["view", "edit"],
      complaints: ["view", "create", "edit"],
      customers: ["view"],
      travel: ["view", "create"],
      leave: ["view", "create"],
      performance: ["view"],
      "crm": ["view", "create", "edit"],
      "jobs": [],
      "admin": [],
      "audit-trail": [],
      "cloth-tracking": [],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    "Store Manager": {
      dashboard: ["view"],
      inventory: ["view", "create", "edit"],
      store: ["view", "create", "edit"],
      "cloth-tracking": ["view", "create"],
      travel: ["view", "create"],
      leave: ["view", "create"],
      approvals: ["view", "approve"],
      "crm": [],
      "jobs": ["view"],
      "admin": [],
      "audit-trail": ["view"],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    "Procurement Manager": {
      dashboard: ["view"],
      procurement: ["view", "create", "edit", "approve"],
      inventory: ["view"],
      travel: ["view", "create"],
      leave: ["view", "create"],
      approvals: ["view", "approve"],
      "crm": [],
      "jobs": [],
      "admin": [],
      "audit-trail": ["view"],
      "cloth-tracking": ["view"],
      "store-manager": ["view"],
      "payroll-self-service": ["view"],
    },

    Accounts: {
      dashboard: ["view"],
      finance: ["view", "create", "edit"],
      accounts: ["view", "create", "edit"],
      travel: ["view", "create"],
      leave: ["view", "create"],
      approvals: ["view"],
      advance: ["view"],
      "crm": [],
      "jobs": [],
      "admin": [],
      "audit-trail": ["view", "export"],
      "cloth-tracking": [],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    HR: {
      dashboard: ["view"],
      users: ["view", "create", "edit"],
      hr: ["view", "create", "edit", "approve"],
      advance: ["view", "create", "edit"],
      travel: ["view", "create"],
      leave: ["view", "create", "approve"],
      approvals: ["view", "approve"],
      performance: ["view"],
      payroll: ["view", "create", "edit", "export"],
      "crm": [],
      "jobs": [],
      "admin": [],
      "audit-trail": ["view", "export"],
      "cloth-tracking": [],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    Manager: {
      dashboard: ["view"],
      users: ["view"],
      leads: ["view", "create", "edit"],
      customers: ["view", "create", "edit"],
      operations: ["view", "create", "edit"],
      complaints: ["view", "create", "edit"],
      travel: ["view", "create"],
      leave: ["view", "create", "approve"],
      approvals: ["view"],
      performance: ["view"],
      "crm": ["view", "create", "edit", "export"],
      "jobs": ["view", "create", "edit"],
      "admin": [],
      "audit-trail": ["view"],
      "cloth-tracking": ["view"],
      "store-manager": [],
      "payroll-self-service": ["view"],
    },

    "Marketing Agency": {
      dashboard: ["view"],
      crm: ["view"],
      leads: ["view"],
      performance: ["view", "export"],
      analytics: ["view", "export"],
      reports: ["view", "export"],
      hr: ["view"],
      // Explicitly NO permissions on sensitive modules:
      finance: [],
      accounts: [],
      payroll: [],
      users: [],
      admin: [],
      "audit-trail": [],
      inventory: [],
      procurement: [],
      advance: [],
      approvals: [],
    },
  },
};

/**
 * Get default city if none specified
 */
export function getDefaultCity(): City {
  return "CITY-SURAT";
}
