/**
 * syncPlanPrices.ts
 *
 * Bridges the two plan-price storage systems so they are ALWAYS in sync:
 *
 *   AdminPlanManagement  →  PLAN_TIERS  (DataService)
 *   SuperAdminPlanEditor →  cleancar_plan_page_config  (localStorage)
 *
 * Direction of authority: PLAN_TIERS is the source of truth for prices.
 * plan_page_config is the display layer. This util keeps them identical.
 *
 * Call syncPlanPricesToPageConfig() after any PLAN_TIERS save.
 * Call syncPageConfigToPlanTiers() after any plan_page_config price edit.
 * Call reconcilePlanPricesOnStartup() once on app load.
 */

import { DataService } from "../services/DataService";
import type { PlanTier } from "../types/subscriptionPlans.types";

// ── Storage keys ──────────────────────────────────────────────────────────────
const PLAN_TIERS_KEY  = "PLAN_TIERS";
const PAGE_CONFIG_KEY = "cleancar_plan_page_config";

// ── Plan ID mappings ───────────────────────────────────────────────────────────
// plan_page_config uses "water" / "shampoo" / "wax" as plan IDs
// PLAN_TIERS uses PlanTierName enum values
const PAGE_ID_TO_TIER_NAME: Record<string, string> = {
  water:   "EXPRESS_WASH",
  shampoo: "SMART_WASH",
  wax:     "ELITE_WASH",
};
const TIER_NAME_TO_PAGE_ID: Record<string, string> = {
  EXPRESS_WASH: "water",
  SMART_WASH:   "shampoo",
  ELITE_WASH:   "wax",
};

// ── Vehicle category ID mappings ───────────────────────────────────────────────
// IDs generated by subscriptionPlansService.getVehicleCategories() via Object.entries()
// vc-1 = Hatchback / Compact Sedan
// vc-2 = SUV / MUV / Sedan
// vc-3 = Luxury / Large SUV
const VCID_TO_PRICE_KEY: Record<string, "hatchback" | "suv" | "luxury"> = {
  "vc-1": "hatchback",
  "vc-2": "suv",
  "vc-3": "luxury",
};
const PRICE_KEY_TO_VCID: Record<string, string> = {
  hatchback: "vc-1",
  suv:       "vc-2",
  luxury:    "vc-3",
};

// ─────────────────────────────────────────────────────────────────────────────
// PLAN_TIERS  →  plan_page_config
// ─────────────────────────────────────────────────────────────────────────────

/**
 * After any save in AdminPlanManagement, call this to push new prices
 * into plan_page_config so the customer-facing buy page is immediately updated.
 */
export function syncPlanPricesToPageConfig(): void {
  try {
    const tiers = DataService.get<PlanTier>(PLAN_TIERS_KEY);
    if (!tiers.length) return;

    // Build patch: { pageId → { hatchback: n, suv: n, luxury: n } }
    const patch: Record<string, Record<string, number>> = {};
    for (const tier of tiers) {
      if (!tier.isActive) continue;
      const pageId   = TIER_NAME_TO_PAGE_ID[tier.name];
      const priceKey = VCID_TO_PRICE_KEY[tier.vehicleCategoryId];
      if (!pageId || !priceKey) continue;
      patch[pageId]           ??= {};
      patch[pageId][priceKey]  = tier.baseMonthlyPrice;
    }
    if (!Object.keys(patch).length) return;

    // Read current plan_page_config
    let pageConfig: any = {};
    try {
      const raw = localStorage.getItem(PAGE_CONFIG_KEY);
      if (raw) pageConfig = JSON.parse(raw);
    } catch { /* corrupt config — start fresh */ }

    // Apply price patch to monthlyPlans array
    const monthlyPlans: any[] = pageConfig.monthlyPlans ?? [];
    let changed = false;
    for (const plan of monthlyPlans) {
      const planPatch = patch[plan.id];
      if (!planPatch) continue;
      for (const [key, val] of Object.entries(planPatch)) {
        if (plan.prices?.[key] !== val) {
          plan.prices = { ...(plan.prices ?? {}), [key]: val };
          changed = true;
        }
      }
    }
    if (!changed) return;

    localStorage.setItem(PAGE_CONFIG_KEY, JSON.stringify(pageConfig));

    // Tell CustomerPlanPage to hot-reload
    window.dispatchEvent(new Event("planConfigUpdated"));
    window.dispatchEvent(new StorageEvent("storage", { key: PAGE_CONFIG_KEY }));

    console.log("[syncPlanPrices] plan_page_config prices synced from PLAN_TIERS ✓", patch);
  } catch (e) {
    console.error("[syncPlanPrices] syncPlanPricesToPageConfig failed:", e);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// plan_page_config  →  PLAN_TIERS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * After any monthlyPlan price edit in SuperAdminPlanEditor, call this to push
 * the new prices into PLAN_TIERS so the ERP (Finance, CRM, Incentive) reflects them.
 */
export function syncPageConfigToPlanTiers(): void {
  try {
    const raw = localStorage.getItem(PAGE_CONFIG_KEY);
    if (!raw) return;
    const pageConfig    = JSON.parse(raw);
    const monthlyPlans: any[] = pageConfig.monthlyPlans ?? [];
    if (!monthlyPlans.length) return;

    const tiers = DataService.get<PlanTier>(PLAN_TIERS_KEY);
    if (!tiers.length) return;

    let changed = false;
    const updatedTiers = tiers.map(tier => {
      const pageId   = TIER_NAME_TO_PAGE_ID[tier.name];
      const priceKey = VCID_TO_PRICE_KEY[tier.vehicleCategoryId];
      if (!pageId || !priceKey) return tier;

      const plan     = monthlyPlans.find((p: any) => p.id === pageId);
      const newPrice = plan?.prices?.[priceKey];
      if (typeof newPrice !== "number" || newPrice === tier.baseMonthlyPrice) return tier;

      changed = true;
      return {
        ...tier,
        baseMonthlyPrice: newPrice,
        costPerWash: Number((newPrice / Math.max(1, tier.washesPerMonth || 26)).toFixed(2)),
      };
    });

    if (!changed) return;

    DataService.setAll(PLAN_TIERS_KEY, updatedTiers);

    // Notify ERP contexts
    window.dispatchEvent(new CustomEvent("cc360_plan_price_changed"));

    console.log("[syncPlanPrices] PLAN_TIERS synced from plan_page_config ✓");
  } catch (e) {
    console.error("[syncPlanPrices] syncPageConfigToPlanTiers failed:", e);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// STARTUP RECONCILE
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Call once on app start (in main.tsx after seed, before React mounts).
 * PLAN_TIERS wins if both stores exist — it is the admin-facing source of truth.
 */
export function reconcilePlanPricesOnStartup(): void {
  try {
    const tiers = DataService.get<PlanTier>(PLAN_TIERS_KEY);
    const raw   = localStorage.getItem(PAGE_CONFIG_KEY);
    if (tiers.length > 0 && raw) {
      // Both populated: push canonical PLAN_TIERS into page_config
      syncPlanPricesToPageConfig();
    } else if (tiers.length === 0 && raw) {
      // Only page_config exists (edge case): push into PLAN_TIERS
      syncPageConfigToPlanTiers();
    }
    // If neither: seed will handle both; no action needed
  } catch (e) {
    console.error("[syncPlanPrices] startup reconcile failed:", e);
  }
}
